// Declarations for the existing CarbonShunts software drawing adapter.
#pragma once

void ForceUpdateMain(void);
void LWSetArrowCursor(void);
void LWSetDialogPort(DialogPtr theDialog);
void LWGetScreenRect(Rect *rect);
const BitMap *LWPortCopyBits(CGrafPtr port);
OSErr LWGetDialogControl(DialogRef inDialog, SInt16 inItemNo, ControlRef *outControl);
void LWGetPortForeColor(CGrafPtr port, RGBColor *color);
void LWGetPortBackColor(CGrafPtr port, RGBColor *color);
void LWGetPortBounds(CGrafPtr port, Rect *bounds);
void LWGetPortPenLocation(CGrafPtr port, Point *point);
void LWGetWindowBounds(WindowRef window, Rect *bounds);
Boolean LWIsControlActive(ControlHandle control);
Boolean LWIsMenuItemEnabled(MenuRef menu, MenuItemIndex item);
void LWDisableMenuItem(MenuRef theMenu, short item);
void LWEnableMenuItem(MenuRef theMenu, short item);
OSStatus LWValidWindowRect(WindowRef window, const Rect *bounds);
OSStatus LWInvalWindowRect(WindowRef window, const Rect *bounds);
Boolean GoodHandle(Handle h);
void LWBlockZero(void *destPtr, Size byteCount);
void DefineDefaultItem(DialogPtr theDialog, short item);
void BlockMove(const void *srcPtr, void *destPtr, Size byteCount);
void BlockMoveData(const void *srcPtr, void *destPtr, Size byteCount);
short Random(void);
void NumToString(long theNum, Str255 theString);
void SysBeep(short duration);
Size FreeMem(void);
Size MaxMem(Size *grow);
void GetIndString(StringPtr theString, short strListID, short index);
void GetFNum(ConstStr255Param fontName, short *theNum);
short StringWidth(ConstStr255Param text);
void DrawString(ConstStr255Param text);
void DrawText(const void *textBuf, short firstByte, short byteCount);
void TextFont(short font);
void TextSize(short size);
void TextFace(short face);
void TextMode(short mode);
void ForeColor(long color);
void BackColor(long color);
void RGBForeColor(const RGBColor *color);
void RGBBackColor(const RGBColor *color);
void OpColor(const RGBColor *color);
void MoveTo(short h, short v);
void LineTo(short h, short v);
void PenMode(short mode);
void PenSize(short width, short height);
void PaintRect(const Rect *rect);
void EraseRect(const Rect *rect);
void FrameRect(const Rect *rect);
void FrameRoundRect(const Rect *rect, short ovalWidth, short ovalHeight);
void InvertRect(const Rect *rect);
void ClipRect(const Rect *rect);
void ScrollRect(const Rect *rect, short dh, short dv, RgnHandle updateRgn);
void BeginUpdate(WindowRef window);
void EndUpdate(WindowRef window);
void InvalWindowRect(WindowRef window, const Rect *bounds);
void QDFlushPortBuffer(CGrafPtr port, RgnHandle region);
void GetMouse(Point *mouseLoc);
Boolean StillDown(void);
Boolean TrackGoAway(WindowRef window, Point point);
void LocalToGlobal(Point *point);
void GlobalToLocal(Point *point);
void GetPort(GrafPtr *port);
void SetPort(GrafPtr port);
void SetPortWindowPort(WindowRef window);
CGrafPtr GetWindowPort(WindowRef window);
WindowRef NewCWindow(void *wStorage, const Rect *boundsRect, ConstStr255Param title, Boolean visible, short procID, WindowRef behind, Boolean goAwayFlag, long refCon);
WindowRef NewWindow(void *wStorage, const Rect *boundsRect, ConstStr255Param title, Boolean visible, short procID, WindowRef behind, Boolean goAwayFlag, long refCon);
OSStatus SetWindowContentColor(WindowRef window, const RGBColor *color);
Boolean IsWindowModified(WindowRef window);
OSStatus GetWindowProxyFSSpec(WindowRef window, FSSpec *file);
DialogRef GetNewDialog(short dialogID, void *dStorage, WindowRef behind);
void DisposeDialog(DialogRef dialog);
void ModalDialog(ModalFilterUPP modalFilter, short *itemHit);
void GetDialogItemText(Handle item, Str255 text);
void SetDialogItemText(Handle item, ConstStr255Param text);
void SelectDialogItemText(DialogRef dialog, short itemNo, short strtSel, short endSel);
short Alert(short alertID, ModalFilterUPP modalFilter);
OSStatus StandardAlert(AlertType alertType, ConstStr255Param error, ConstStr255Param explanation, const AlertStdAlertParamRec *param, short *itemHit);
void AppendMenu(MenuRef menu, ConstStr255Param data);
void AppendResMenu(MenuRef menu, ResType resType);
MenuRef GetNewMBar(short menuBarID);
void SetMenuBar(MenuRef menuList);
long MenuKey(short ch);
OSStatus EnableMenuCommand(MenuRef menu, MenuCommand commandID);
MenuRef GetControlPopupMenuHandle(ControlRef control);
short GetControlValue(ControlRef control);
void SetControlMaximum(ControlRef control, short maxValue);
void SetControlTitle(ControlRef control, ConstStr255Param title);
void GetControlTitle(ControlRef control, Str255 title);
CursHandle GetCursor(short cursorID);
void SetCursor(const void *cursor);
void GetPen(Point *point);
OSErr NewGWorld(GWorldPtr *offscreenGWorld, short pixelDepth, const Rect *boundsRect, CTabHandle cTable, GDHandle aGDevice, GWorldFlags flags);
void DisposeGWorld(GWorldPtr offscreenGWorld);
void GetGWorld(CGrafPtr *port, GDHandle *gdh);
void SetGWorld(CGrafPtr port, GDHandle gdh);
PixMapHandle GetGWorldPixMap(GWorldPtr offscreenGWorld);
Boolean LockPixels(PixMapHandle pm);
Ptr GetPixBaseAddr(PixMapHandle pixels);
void UnlockPixels(PixMapHandle pm);
void CopyBits(const BitMap *srcBits, const BitMap *dstBits, const Rect *srcRect, const Rect *dstRect, short mode, RgnHandle maskRgn);
void CopyMask(const BitMap *srcBits, const BitMap *maskBits, const BitMap *dstBits, const Rect *srcRect, const Rect *maskRect, const Rect *dstRect);
Boolean U3LegacyBitmapSelfTest(void);
Boolean U3LegacyDrawImageURL(CFURLRef url, CGrafPtr port, const Rect *bounds,
                             int columns, int rows);
void GetCPixel(short h, short v, RGBColor *pixel);
void GetClip(RgnHandle rgn);
void SetClip(RgnHandle rgn);
PolyHandle OpenPoly(void);
void ClosePoly(void);
void PaintPoly(PolyHandle poly);
void KillPoly(PolyHandle poly);
PicHandle GetPicture(short pictureID);
void DrawPicture(PicHandle myPicture, const Rect *dstRect);
OSStatus GetThemeTextDimensions(CFStringRef string, ThemeFontID fontID, ThemeDrawState state, Boolean wrapToWidth, Point *bounds, short *baseline);
OSStatus DrawThemeTextBox(CFStringRef string, ThemeFontID fontID, ThemeDrawState state, Boolean wrapToWidth, const Rect *bounds, SInt16 justification, CGContextRef context);
OSErr GetGraphicsImporterForFile(const FSSpec *file, ComponentInstance *gi);
OSErr GraphicsImportSetGWorld(ComponentInstance gi, CGrafPtr port, GDHandle gdh);
OSErr GraphicsImportSetBoundsRect(ComponentInstance gi, const Rect *bounds);
OSErr GraphicsImportGetBoundsRect(ComponentInstance gi, Rect *bounds);
OSErr GraphicsImportDraw(ComponentInstance gi);
OSErr FSMakeFSSpec(short vRefNum, long dirID, ConstStr255Param fileName, FSSpec *spec);
OSErr FSpDelete(const FSSpec *spec);
void FSpCreateResFile(const FSSpec *spec, OSType creator, OSType fileType, ScriptCode scriptTag);
short FSpOpenResFile(const FSSpec *spec, SignedByte permission);
OSErr FSpMakeFSRef(const FSSpec *spec, FSRef *ref);
OSErr IsAliasFile(const FSSpec *fileFSSpec, Boolean *aliasFileFlag, Boolean *folderFlag);
OSErr ResolveAliasFile(FSSpec *theSpec, Boolean resolveAliasChains, Boolean *targetIsFolder, Boolean *wasAliased);
OSErr GetEOF(short refNum, long *logEOF);
OSErr FSClose(short refNum);
void SetAntiAliasedTextEnabled(Boolean enabled, short minimumSize);
MenuRef GetMenuHandle(MenuID menuID);
void DeleteMenuItem(MenuRef menu, MenuItemIndex item);
void DrawMenuBar(void);
short GetMBarHeight(void);
void MoveWindow(WindowRef window, short hGlobal, short vGlobal, Boolean front);
void SizeWindow(WindowRef window, short w, short h, Boolean update);
void ShowWindow(WindowRef window);
void HideWindow(WindowRef window);
void DisposeWindow(WindowRef window);
void BringToFront(WindowRef window);
RgnHandle NewRgn(void);
void DisposeRgn(RgnHandle rgn);
void RectRgn(RgnHandle rgn, const Rect *rect);
void CopyRgn(RgnHandle srcRgn, RgnHandle dstRgn);
void UnionRgn(RgnHandle srcRgnA, RgnHandle srcRgnB, RgnHandle dstRgn);
void SectRgn(RgnHandle srcRgnA, RgnHandle srcRgnB, RgnHandle dstRgn);
void DiffRgn(RgnHandle srcRgnA, RgnHandle srcRgnB, RgnHandle dstRgn);
Boolean EqualRgn(RgnHandle rgnA, RgnHandle rgnB);
RgnHandle GetGrayRgn(void);
MenuBarHandle GetMCInfo(void);
